if (NOT OPENDDS_FOUND)
  find_package(OpenDDS)
endif()

set(CMAKE_OPENDDS_IDL_COMPILER "${OPENDDS_IDL}")
mark_as_advanced(CMAKE_OPENDDS_IDL_COMPILER)
set(CMAKE_OPENDDS_IDL_SOURCE_FILE_EXTENSIONS idl)
set(CMAKE_OPENDDS_IDL_COMPILER_ENV_VAR "OPENDDS_IDL")

configure_file(
  ${CMAKE_CURRENT_LIST_DIR}/CMakeOPENDDS_IDLCompiler.cmake.in
  ${CMAKE_PLATFORM_INFO_DIR}/CMakeOPENDDS_IDLCompiler.cmake
)
