if(NOT CMAKE_OPENDDS_IDL_COMPILE_OBJECT)
  set(CMAKE_OPENDDS_IDL_COMPILE_OBJECT "<CMAKE_OPENDDS_IDL_COMPILER> <SOURCE>")
  CMAKE_OPENDDS_IDL_CREATE_SHARED_LIBRARY
  CMAKE_OPENDDS_IDL_CREATE_SHARED_MODULE
  CMAKE_OPENDDS_IDL_CREATE_STATIC_LIBRARY
  CMAKE_OPENDDS_IDL_COMPILE_OBJECT
  CMAKE_OPENDDS_IDL_LINK_EXECUTABLE
endif()
set(CMAKE_OPENDDS_IDL_INFORMATION_LOADED 1)
