name: "Insert PR Number into News"

on:
  push:
    paths:
      - 'docs/news.d/**'

jobs:
  insert_news_pr_num:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout OpenDDS
      uses: actions/checkout@v3
    - name: Update PR
      run: python3 docs/news.py insert-pr-num
      env:
        GH_TOKEN: ${{ github.token }}
