name: "Insert PR Number into News"

on:
  pull_request:
    paths:
      - 'docs/news.d/**'
    types: [closed]

jobs:
  insert_news_pr_num:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout OpenDDS
      uses: actions/checkout@v3
    - name: Update PR
      run: python3 docs/news.py insert-pr-num ${{github.event.pull_request.number}}
